/* Load the presentation layer after the base stylesheet, then establish the saved theme. */
const premiumStyles = document.createElement('link'); premiumStyles.rel = 'stylesheet'; premiumStyles.href = 'premium.css'; document.head.append(premiumStyles);
const themePaint = document.createElement('style'); themePaint.textContent = 'body[data-theme="light"]{background:radial-gradient(ellipse at 14% -10%,#d8d4ff 0%,transparent 43%),radial-gradient(ellipse at 92% 35%,#c3e4ff 0%,transparent 36%),#f5f2ec!important;color:#121a2c!important}body[data-theme="dark"]{background:#070b16!important}'; document.head.append(themePaint);
const Theme = (() => {
  const key = 'lectureHubTheme';
  const effective = value => value === 'system' ? (matchMedia('(prefers-color-scheme: light)').matches ? 'light' : 'dark') : value;
  // A first visit follows the operating system; the portal's unconfigured paint remains dark.
  const get = () => localStorage.getItem(key) || 'system';
  const apply = value => { document.body.dataset.theme = effective(value); document.documentElement.dataset.theme = effective(value); document.querySelectorAll('.theme-option').forEach(b => b.classList.toggle('active', b.dataset.theme === value)); const icon = $('.theme-toggle'); if (icon) { icon.textContent = effective(value) === 'dark' ? '☾' : '☀'; icon.setAttribute('aria-label', `Theme: ${value}`); } };
  const mount = () => { const nav = $('.nav'); if (!nav || $('.theme-control')) return; const control=document.createElement('div'); control.className='theme-control'; control.innerHTML=`<button class="theme-toggle" aria-label="Theme">☾</button><div class="theme-popover" role="menu"><button class="theme-option" data-theme="dark">☾  DARK</button><button class="theme-option" data-theme="light">☀  LIGHT</button><button class="theme-option" data-theme="system">◐  SYSTEM</button></div>`; nav.append(control); $('.theme-toggle',control).onclick=()=>control.classList.toggle('open'); document.addEventListener('click',e=>{if(!control.contains(e.target))control.classList.remove('open')}); control.querySelectorAll('.theme-option').forEach(b=>b.onclick=()=>{localStorage.setItem(key,b.dataset.theme);apply(b.dataset.theme);control.classList.remove('open')}); apply(get()); };
  matchMedia('(prefers-color-scheme: light)').addEventListener?.('change',()=>get()==='system'&&apply('system'));
  return { mount, apply };
})();
const CATEGORIES = ['MODULE 1','MODULE 2','MODULE 3','WORKSHOPS','OPTIONAL CLASSES'];
const $ = (s, e=document) => e.querySelector(s);
const clean = x => String(x ?? '').trim();
const val = (o, ...keys) => keys.map(k => o[k] ?? o[k.toLowerCase()] ?? o[k.replace(/ /g,'')]).find(v => v !== undefined) ?? '';
const lecture = (raw, category='') => ({ name: clean(val(raw,'Lecture Name','lectureName','name','title')), instructor: clean(val(raw,'Instructor Name','instructorName','instructor')), date: clean(val(raw,'Date','date')), link: clean(val(raw,'Link','link','url')), status: clean(val(raw,'Status','status')) || 'ARCHIVED', category: clean(val(raw,'Module','module','Category','category')) || category });
const escape = t => String(t).replace(/[&<>'"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function skeleton(n=6) { return Array.from({length:n},()=>'<article class="lecture-card skeleton"><i></i><i></i><i></i></article>').join(''); }
function card(x) { const status=x.status.toUpperCase(); return `<article class="lecture-card tilt"><div class="card-top"><span>${escape(x.category)}</span><b class="status ${status.toLowerCase()}">${escape(status)}</b></div><h3>${escape(x.name || 'Untitled lecture')}</h3><dl><div><dt>DATE</dt><dd>${escape(x.date || 'To be announced')}</dd></div><div><dt>INSTRUCTOR</dt><dd>${escape(x.instructor || 'Not listed')}</dd></div></dl>${x.link ? `<a class="access ripple" target="_blank" rel="noopener" href="${escape(x.link)}" data-log="LECTURE_ACCESS">ACCESS LECTURE <b>↗</b></a>` : '<span class="access unavailable">LINK PENDING</span>'}</article>`; }
function error(target, message='DATABASE CONNECTION ISSUE') { target.innerHTML=`<div class="empty-state"><b>◌</b><h3>${message}</h3><p>We couldn’t reach the lecture archive right now.</p><button class="button outline retry">TRY AGAIN</button></div>`; $('.retry',target)?.addEventListener('click',()=>location.reload()); }
function renderLectures(target, records, filters={}) { let a=records.filter(x=>[x.name,x.instructor,x.date,x.status,x.category].join(' ').toLowerCase().includes((filters.query||'').toLowerCase())); if(filters.status && filters.status!=='ALL') a=a.filter(x=>x.status.toUpperCase()===filters.status); const dir=filters.sort==='Oldest'?1:-1; if(filters.sort==='Lecture Name')a.sort((a,b)=>a.name.localeCompare(b.name)); else if(filters.sort==='Instructor')a.sort((a,b)=>a.instructor.localeCompare(b.instructor)); else a.sort((a,b)=>dir*(new Date(b.date||0)-new Date(a.date||0))); target.innerHTML=a.length?a.map(card).join(''):'<div class="empty-state"><b>⌕</b><h3>NO LECTURES FOUND</h3><p>Try changing your filters or search terms.</p></div>'; $('#found') && ($('#found').textContent=`${a.length} lecture${a.length===1?'':'s'} found`); Motion.init(); bindLogLinks(); }
function bindLogLinks() { document.querySelectorAll('[data-log]').forEach(a=>a.onclick=()=>API.log(a.dataset.log, a.href||'')); }
async function initCatalog() { const grid=$('#lecture-grid'); if(!grid)return; grid.innerHTML=skeleton(); let records=[]; const category=document.body.dataset.category||''; try { records=(category?await API.lectures(category):await API.allLectures()).map(x=>lecture(x,category)); } catch { error(grid); return; } const f={query:'',status:'ALL',sort:'Newest'}; const refresh=()=>renderLectures(grid,records,f); $('#search')?.addEventListener('input',e=>{f.query=e.target.value;API.log('SEARCH',f.query);refresh()}); $('#status')?.addEventListener('change',e=>{f.status=e.target.value;refresh()}); $('#sort')?.addEventListener('change',e=>{f.sort=e.target.value;refresh()}); refresh(); }
async function initHome() { const latest=$('#latest-grid'), numbers=$('#stats'); if(!latest)return; latest.innerHTML=skeleton(3); try { const [all,st]=await Promise.all([API.allLectures(),API.stats().catch(()=>({}))]); const entries=all.map(x=>lecture(x)); renderLectures(latest,entries.slice(0,6)); const categories=new Set(entries.map(x=>x.category)); const fields=[['TOTAL LECTURES',st.totalLectures??entries.length],['MODULES',st.modules??[...categories].filter(x=>x.startsWith('MODULE')).length],['WORKSHOPS',st.totalWorkshops??entries.filter(x=>x.category==='WORKSHOPS').length],['OPTIONAL CLASSES',st.totalOptionalClasses??entries.filter(x=>x.category==='OPTIONAL CLASSES').length]]; numbers.innerHTML=fields.map(([l,n])=>`<div><strong data-number="${Number(n)||0}">0</strong><span>${l}</span></div>`).join(''); document.querySelectorAll('[data-number]').forEach(e=>{const end=+e.dataset.number,start=performance.now();requestAnimationFrame(function go(t){e.textContent=Math.round(Math.min(1,(t-start)/900)*end);if(t-start<900)requestAnimationFrame(go)})}); } catch { error(latest); } }
async function initSettingsPage(type) { const root=$('#dynamic-content'); try {const s=await API.settings(); $('#announce') && s.ANNOUNCEMENT && ($('#announce').innerHTML=`<b>✦ ANNOUNCEMENT</b><span>${escape(s.ANNOUNCEMENT)}</span>`); if(String(s.MAINTENANCE_MODE).toUpperCase()==='TRUE'){document.body.innerHTML='<main class="maintenance"><span class="eyebrow">LECTURE HUB</span><h1>We are refining<br>the archive.</h1><p>Maintenance is in progress. Please return shortly.</p></main>';return;} if(!root)return; if(type==='notes') root.innerHTML=`<span class="eyebrow">CURATED FOR DEEP WORK</span><h1>NOTES &amp; RESOURCES</h1><p class="lede">Your shared learning materials, all in one place.</p><div class="resource-card"><span>MEGA VAULT</span><h2>Lecture notes archive</h2><label>DECRYPTION PASSWORD</label><code id="key">${escape(s.MEGA_DECRYPTION_KEY||'Not available')}</code><div><a class="button primary ripple" target="_blank" rel="noopener" href="${escape(s.MEGA_NOTES_LINK||'#')}" data-log="MEGA_CLICK">OPEN MEGA NOTES ↗</a><button class="button outline ripple" id="copy">COPY PASSWORD</button></div></div>`; else root.innerHTML=`<span class="eyebrow">LET’S CONNECT</span><h1>CONTACT</h1><p class="lede">For questions, requests, or help with the archive.</p><div class="contact-card"><h2>${escape(s.CONTACT_NAME||'Contact details')}</h2><p>${escape(s.CONTACT_EMAIL||'Email unavailable')}</p><div class="contact-actions">${s.CONTACT_EMAIL?`<a data-log="CONTACT_OPENED" class="button primary" href="mailto:${escape(s.CONTACT_EMAIL)}">EMAIL ↗</a>`:''}${s.CONTACT_PHONE?`<a data-log="CONTACT_OPENED" class="button outline" href="tel:${escape(s.CONTACT_PHONE)}">CALL ↗</a>`:''}${s.CONTACT_TELEGRAM?`<a data-log="CONTACT_OPENED" target="_blank" class="button outline" href="${escape(s.CONTACT_TELEGRAM)}">TELEGRAM ↗</a>`:''}</div>${s.UPI_PAYMENT_LINK?`<a data-log="DONATE_CLICK" target="_blank" class="donate" href="${escape(s.UPI_PAYMENT_LINK)}">DONATE / SUPPORT THIS PROJECT ↗</a>`:''}</div>`; $('#copy')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(s.MEGA_DECRYPTION_KEY||'');$('#copy').textContent='✓ COPIED';API.log('NOTES_OPENED')}); bindLogLinks(); }catch{root && error(root);} }
async function initAdmin(){const root=$('#admin-content');if(!root)return; await Auth.gate(true); root.innerHTML=skeleton(4);try{const [all,stats,logs,settings]=await Promise.all([API.allLectures(),API.stats(),API.logs(),API.settings()]);const rows=all.map(x=>lecture(x));const stat=[['TOTAL VISITS',stats.totalVisits],['TODAY VISITS',stats.todayVisits],['UNIQUE VISITORS',stats.uniqueVisitors],['SUCCESSFUL LOGINS',stats.successfulLogins],['TOTAL LECTURES',stats.totalLectures??rows.length],['TOTAL WORKSHOPS',stats.totalWorkshops??rows.filter(x=>x.category==='WORKSHOPS').length]];root.innerHTML=`<section class="admin-overview"><div class="admin-head"><span class="eyebrow">ADMINISTRATOR CONSOLE</span><h1>Archive intelligence.</h1></div><div class="stat-grid">${stat.map(([x,n])=>`<div><span>${x}</span><b>${n??'—'}</b></div>`).join('')}</div></section><section class="admin-section"><h2>LECTURES</h2><div id="admin-grid" class="lecture-grid">${rows.map(card).join('')}</div></section><section class="admin-section"><h2>ACTIVITY LOG</h2><div class="log-table"><table><thead><tr>${['Timestamp','Event','Page','Status','Visitor ID','Details','User Agent'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${logs.slice(0,50).map(l=>`<tr>${[val(l,'Timestamp','timestamp'),val(l,'Event','event'),val(l,'Page','page'),val(l,'Status','status'),val(l,'Visitor ID','visitorId'),val(l,'Details','details'),val(l,'User Agent','userAgent')].map(x=>`<td>${escape(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="admin-section"><h2>SETTINGS</h2><p class="admin-note">Settings are read from Google Sheets. ${typeof settings.updateSettings==='undefined'?'EDIT IN GOOGLE SHEETS':''}</p><div class="settings-grid">${['SITE_NAME','SITE_TAGLINE','MEGA_NOTES_LINK','MEGA_DECRYPTION_KEY','CONTACT_NAME','CONTACT_EMAIL','CONTACT_PHONE','CONTACT_TELEGRAM','UPI_PAYMENT_LINK','ANNOUNCEMENT','WEBSITE_VERSION','MAINTENANCE_MODE'].map(k=>`<label>${k}<input data-setting="${k}" value="${escape(settings[k]||'')}"></label>`).join('')}</div><button id="save-settings" class="button primary">SAVE SETTINGS</button></section>`; $('#save-settings').onclick=async()=>{const s=Object.fromEntries([...document.querySelectorAll('[data-setting]')].map(x=>[x.dataset.setting,x.value]));try{await API.updateSettings(s);$('#save-settings').textContent='✓ SAVED';}catch{$('.admin-note').textContent='EDIT IN GOOGLE SHEETS';}};Motion.init();}catch{error(root)}}
document.addEventListener('DOMContentLoaded',async()=>{Theme.mount();if($('.hero')&&!$('.hero-scroll'))$('.hero').insertAdjacentHTML('beforeend','<span class="hero-scroll">SCROLL TO EXPLORE</span>');Motion.init();if(!document.body.classList.contains('admin'))await Auth.gate();API.visit();API.log('PAGE_VIEW');await initSettingsPage(document.body.dataset.page);initHome();initCatalog();initAdmin();});
